### ISSUE TITLE
Pokecenter issues

### ISSUE THREAD

**Issue by boblovespi** [DaBlob/Pokemon-Blobsanity#1]
There appears to be bugs with the pokecenters, such as the lady disappearing or being backwards
![2017-03-19 12](https://cloud.githubusercontent.com/assets/22250834/24084821/887df524-0cae-11e7-97ef-a5cf107eaacd.png)
![2017-03-19 13](https://cloud.githubusercontent.com/assets/22250834/24084819/88417518-0cae-11e7-983d-d586b1e58e26.png)
![2017-03-19 1](https://cloud.githubusercontent.com/assets/22250834/24084818/8841539e-0cae-11e7-87a5-ea958a004cd7.png)

**Comment by DaBlob** [comment]
ok, I'm on to fixing that
