### ISSUE TITLE
Invisible block

### ISSUE THREAD

**Issue by boblovespi** [DaBlob/Pokemon-Blobsanity#3]
In the prof's lab, there is an invisible block
![2017-03-19 20](https://cloud.githubusercontent.com/assets/22250834/24084924/416b8d2a-0cb0-11e7-8130-42e1e5cd7d15.png)
![2017-03-19 19](https://cloud.githubusercontent.com/assets/22250834/24084925/416c232a-0cb0-11e7-9858-f18aa3c51d05.png)
![2017-03-19 21](https://cloud.githubusercontent.com/assets/22250834/24084926/416cda18-0cb0-11e7-8846-a7faa35e57c1.png)

**Comment by DaBlob** [comment]
thats the professor.
