### ISSUE TITLE
staat

### ISSUE THREAD

**Issue by gruff218** [DaBlob/Pokemon-Blobsanity#7]
can u make it so stat modifiers show up on screen?

**Comment by Pokelord248** [comment]
![image](https://cloud.githubusercontent.com/assets/27631280/25074107/38e83c02-22a9-11e7-8c5a-6b0d16441aa8.png)

**Comment by Pokelord248** [comment]
![image](https://cloud.githubusercontent.com/assets/27631280/25074133/c9b3f00a-22a9-11e7-9a71-8e5c7a901cbf.png)

**Comment by Pokelord248** [comment]
![image](https://cloud.githubusercontent.com/assets/27631280/25074137/e31e5bd4-22a9-11e7-9cee-7647247b4eb6.png)

**Comment by Pokelord248** [comment]
![image](https://cloud.githubusercontent.com/assets/27631280/25074179/4f1cc794-22aa-11e7-8b0c-c71e84404dc7.png)
Its marvelous not marelous

**Comment by Pokelord248** [comment]
![image](https://cloud.githubusercontent.com/assets/27631280/25074498/dfcba836-22b0-11e7-9e70-a6bdcc70b371.png)
Text glitch in cave

**Comment by boblovespi** [comment]
put your issues in a new issue
