### ISSUE TITLE
Game crashes when your character is beaten.

### ISSUE THREAD

**Issue by MarcTheMan** [DaBlob/Pokemon-Blobsanity#9]
OMG PLZ FX NOW I CAN'T LIVE WITHOUT DYING IF THAT MAKES ANYSENSE WHATSOEVER HALLP

**Comment by MarcTheMan** [comment]
[](u
<img width="746" alt="capture1234567890" src="https://cloud.githubusercontent.com/assets/28166043/25557321/187e7484-2cc4-11e7-9210-293cce0271d6.PNG">
rl)

**Comment by MarcTheMan** [comment]
[](url)
<img width="125" alt="capture345" src="https://cloud.githubusercontent.com/assets/28166043/25557499/6d573f74-2cc7-11e7-9711-6b409f101f04.PNG">

**Comment by MarcTheMan** [comment]
Why is my blobfish bright pink?

**Comment by MarcTheMan** [comment]
I got defeated again and now i'm in a wall

**Comment by MarcTheMan** [comment]
[](url)
<img width="760" alt="capture90" src="https://cloud.githubusercontent.com/assets/28166043/25557525/fc427ff0-2cc7-11e7-9dcf-397743c97ad8.PNG">

**Comment by MarcTheMan** [comment]
This time it worked when I died...

**Comment by MarcTheMan** [comment]
[](url)
<img width="757" alt="capture76" src="https://cloud.githubusercontent.com/assets/28166043/25557535/3652e8a6-2cc8-11e7-9a00-2423b6191fa6.PNG">

**Comment by DaBlob** [comment]
1. Stuck in wall - WTF I JUST FIXED THAT I THINK YOU GOT THE WRONG VERSION DOWNLOAD FROM RELICCASTLE NOT THE ONE I SENT YOU
2. Red blobfish -  THATS BECAUSE YOUR BLOBFISH IS BURNED duh
3. Follow pokemon missing emotes - I am gonna contact the maker of the follow pokemon scrip and see if there is a fix or just ask thundaga in a stream

**Comment by MarcTheMan** [comment]
[😓]

________________________________

**Comment by DaBlob** [comment]
What? i barely know ruby!

**Comment by DaBlob** [comment]
and then the debug doesnt give you any clues either

**Comment by DaBlob** [comment]
also, did u download from reliccastle?

**Comment by DaBlob** [comment]
if u want to avoid wall insides, i reccomend u heal at a pokecenter and if its fixed in your version well good for u when i find a fix for the following pokemon ill add a new patch

**Comment by DaBlob** [comment]
Fixed!

**Comment by DaBlob** [comment]
all done!
